### PR TITLE
Allow custom end-of-line

### PR DESCRIPTION
**Pull request by spremi**
Working in mixed-mode repositories, the code may not necessarily follow os defined end-of-line specified
by `grunt.util.linefeed`.
Allow custom 'eol' to be specified by the user.
Default behavior to use `grunt.util.linefeed` is retained.

Unit tests have been added in a separate commit.

### CODE REVIEW

**Comment by nuzzio** [comment]
Thank you, this is quite useful. Nice, clean code.

**Comment by nuzzio** [comment]
@spremi Upon further testing, I found that the functionality you want is not enforceable. 

An inline match in a file with either line endings will still be replaced:
```javascript
function free(a, b, c /* {test} */ , d /* {/test} */) {
```
and become
```javascript
function free(a, b, c) {
```

What I can do is respect line endings that are found, which basically means not changing line endings at all. Just code removal.

**Comment by spremi** [comment]
Do the `test` tags here represent the eol?

I was trying to create test case with mixed line endings, but wasn't successful with my editor & git attribute settings.

**Comment by nuzzio** [comment]
The test tags represent a use case in which there are no newlines or return carriages. In other words, the match is inline. 

This means that regardless of the line ending it will remove the code.

**Pull request merged**
